ANDROID: sdcardfs: fix build with kernel 5.6
Fix build after commit:
d7167b149943 ("fs_parse: fold fs_parameter_desc/fs_parameter_spec")

Fixes the following building errors:

~/pie-x86_kernel/kernel/fs/sdcardfs/main.c:60:21: error: variable 'sdcardfs_parameters' has initializer but incomplete type
~/pie-x86_kernel/kernel/fs/sdcardfs/main.c:61:2: error: unknown field 'name' specified in initializer
...
~/pie-x86_kernel/kernel/fs/sdcardfs/main.c:62:2: error: unknown field 'specs' specified in initializer
make[3]: *** [~/pie-x86_kernel/kernel/scripts/Makefile.build:266: fs/sdcardfs/main.o] Error 1